repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks:
      - id: ruff-format
        name: Format code with ruff
      - id: ruff
        name: Lint with ruff
        args: [--fix, --exit-non-zero-on-fix]
  
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        name: Type check with mypy
        files: ^dlcalc/.*\.py$
        args: [--config-file, pyproject.toml, --ignore-missing-imports]
        additional_dependencies:
          - types-PyYAML>=6.0.1
          - boto3-stubs[ec2]
          - kubernetes-stubs
  
  - repo: local
    hooks:
      - id: pytest
        name: Run tests
        entry: uv run pytest
        language: system
        pass_filenames: false
        args: [tests/, -q]
        types: [python]
  
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-merge-conflict
      - id: debug-statements
        language_version: python3