name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-mfu-prediction:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    
    - name: Run integration tests
      run: |
        pytest tests/integration/ -v
    
    - name: Verify LLaMA-3 70B MFU prediction
      run: |
        # Run the specific MFU test
        pytest tests/integration/test_3dtrn_predictions.py::TestMFUPredictions::test_llama3_70b_mfu -v
        
        # Also verify directly
        output=$(python -m dlcalc.training_3d examples/llama3_70b.yaml 2>&1)
        echo "$output" | grep "predicted MFU: 30.22%" || \
          (echo "MFU test failed - expected 30.22%" && exit 1)